spring:
  application:
    name: footballStatistics


#DB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/football_statistics
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: true

    properties:
      hibernate:
        format-sql: true

#Loggers
  logging:
    level:
      org:
      hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      orm.jdbc.bind: TRACE
